; generated by PrusaSlicer 2.5.0+win64 on 2022-10-22 at 15:05:46 UTC


;
; thumbnail begin 16x16 704
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB10lEQVR4AbVSTYvaUBR9fqIiGkF0Iz
; UgYpFaxxltRvPy8pIXnSQ6DUYqA2667LLL7rp21VIKXc4fKJQuuxCX/Qld+hNcurzNfTAWOjDMDMyF
; C+G9d849554Q8pQVi8UypVLpijymcrncyeDsbCeMEbRard/pdFq9FxCnqs9qHwTTD9ygwBmF0KHQ6/
; X2hULBvROcyWSeay/b20s7AnIumzEmO3QMsPRzqNfr14lEQrkFrlQq7/hwsBfcBNu2YTweg+d5MJ1O
; YTKZyLML2wTLNKDT6ezy+Tw/Sm40GtevhSEnOY4Dvu9DEASwWCxkh2EIs9lM3uEbNyIyRxrUarVPhL
; 3q7Xyug2EYIIQA13UleLlcwmq1ko3f8/lcEqOizWYDv35+hyCyRdwI7JgUKKVgWZZ8hI//J0BSJEdb
; 6/Uavn75DG9850BUVf2haRqM+T8LKBdl31hAMBLjneCRBcGhf3qyPUZbLBavut3u/tLW4cJicmG4OJ
; SLE3GheBY4DDymHarV6sdbKaRSKbXZbG4nbAg3C8VGWxgnRjvovviTzWb5nf9CuVx+3+/3wbPocTdT
; PsL8v2Fi5D4VTTlvt9s7mw5BH5zuFUV5Sx5a8XhcQTXJZFIlT1l/AUXL25OheTdCAAAAAElFTkSuQm
; CC
; thumbnail end
;

;
; thumbnail begin 220x124 21724
; iVBORw0KGgoAAAANSUhEUgAAANwAAAB8CAYAAAACRt5vAAA/a0lEQVR4Ae2deZBdVdnu2xlnFAcUxX
; meB9Jzn+7O0BnInDQZSEISEgIiIioCMivyOYE4gAOKilfvZ6F+H4IIaKF1uddbXr2W+gdlWVerrlVq
; OeFQivP6zm93/07es7JOoLuT0Al7Va063efsYe2917Pfdz3v1NVVt1nTDjvssOc/5znPue0Vr3hFor
; /yla9Mo6OjVR8YGKj6qlWr0ubNm9OJJ56Y1q5d2/re7dz3nvanP/3pn33AAx5weFfd6nZfao973ON2
; vexlL7tLIPT29qaVK1emkZGRClCNRiOdcMIJafny5S2Q8fuOHTuq3/h/3rx5acWKFemYY46ZEuhe9K
; IX/eRRj3rUwq661e1Qb0iXpz3taddEqQbIAI8gWr16ddq6dWuaPzqSzljWlz63tTtdt62n+pttd+3a
; ldatW5cWL17c2gcQTlXaPeUpT7m8q251O1QbUgXp4oTv7u5OCxcuTENDQy0ptnHjxrR+/fo0vmR+uv
; r4ngpoy0d606rR3gp4n9jckzauWFypmUhA9wNwc+fOTa961aumBLrnPve530S17apb3Q6Vdr/73e+w
; o4466vI40QEI6qCAmT9/ftq+fXv1uXVRfwW0d63rTwvm7V7PLVm4IL1rw1C6eWd3tc2CBQvSKaecUn
; 3y++DgYLXm6+/vnxLoUG0f//jHn95Vt7od7A3p8YIXvOCOqEICEFRDJBsSDvXw+OOPTyNDg+nydb3p
; C9u605axvgpEbMc2rOUE1sYFfek/tjcBeVxvmt8YqNTPTZs2paVLl1ZAZh8IFc41FeA961nPuumBD3
; zgkV11q9vB1pBqOTHS09NTgUeJNTw8nLZt25bWrFmTjls0UoHovePHpLFGX2sb1ETIEtZrbO/385pA
; +/DGnmqfLcvnV2roSSed1CJdkHYAFLV1KqB76UtfemdNqNTtoGoPfvCDn460iFJtbGysRXLQly1bVq
; 3B5g430pkr+io18U1rRtrWc0uWLEmLFi1qAx8qZ1y3nTU+N924ozuds7Kv+h8WM6qqxx57bLXfVAmV
; pz71qVfx0uiqW91mc+tEjCBxUPMAHuofTOTKuf0VCfLJ449JS0f7K4AgleiARmkVO6DieAARMHFc9v
; 305u706S091d/j4+OV3Q6Acz5ADFCnYz546EMf+vKuutVttjWkQaT76aiASBfBwuRHArEee8OK/nRD
; UzJdtKonDQ70t7YBTBAfbJuDTVWRtRrHiMceah7j3BU9laR87bLBSk099dRT2yQk5oO+vr6aUKnbwd
; 0gRqJUg5pHHYxrLoiRDRs2pOGhgYoY+Xxz7bV16W4JhhQCRNrjABagi8dAQgI21U5+QxqyrducuHJB
; +s8Te9P7N0wQKpgPIGTiunG65gNU5a661e3eakg13v6RGFFK6XpFh0VE0kDlyy6ODPZXkx9QARrAFt
; dvUSqhDgLgSLhEiccx2I51YXXOof70nvHu6lybxvor1RJjuRKRfTgm3i01oVK3g6LdEz9I1mmspebP
; HUnnr+pNN504J+1a3NsGGCQWKmTcL3ZAye+s10qA1IbHuTQb2E9ZMkHGXLq2t9qXsaBqRhJmOv6YqM
; 61P2bdDliD7udt7wR0XRXVwy1btlTEx8p5A+kz2/rSxzb3NQmN3WCAEOF3VUYmfg4Y/o/MJsCKwOS8
; SD6ZS86LtNPXkr54uD99fFNPi1ABvABP8PLJeaYq7VChH/GIRwx31a1u+6uViBGAgyqHygY4UB2xrf
; E9vo9ImDOXdVfA0ueRbQBKLqkEDPsC4EiKRKCyDb9x3k5qqGtB+xuX96ZbGUvTBAFoGS/nAGwAkPHU
; /ph1mzUtp/tf/epXV5M6Tvizzz47vfnNb05L5g61/CBXjvS2qYfHHXdccS0W1TzCcHJpFzvgQIWMhE
; pJFdUc0VJxR3vTdVvntAiVN77xjemss85qMznUhErd7tWGVDvyyCMvyOn+CAiAh5Tgu9PWjqUvnzqS
; rtjUSMOD7eohEgUAGB0QwVCpf00J6XGZ/NrQIiA4hva53BBe6hwvqqGM6Z3rBtLNpwyk140vrM5x8s
; kntx3HMdTmg7od0AYxwts7EiNMxrhugoTAkI0fJOzj9du70wlNNhK1EmkGSKIfZFQfOQbgpaMexrVX
; nPwAC2DsTQ0t7Wt3fQjAWTeyvty+qC/d0CRxKsa0OXaYVEwXbA9BQwfYU/XHrANc6zbl1skPMhqRmc
; QYlitiZO4E3Y9vox4jdOxuqJh7Uw8BI0RGLu0iMYL6yHadthGY+botVzGRZDFqfEGjv1J9Gfvaef3V
; y+PMM89sMx/w91T9MV/84hf/vDYf1O0etdwPkvUMky5OZt7+SIR5I8Pp7LUjTWKkJ522tG+PdRYqIv
; viVJwDBsmEeghwAQPSLpdS7KuhW0l2d+s2tsmBKZHDuUqEyunNsd/UJFQu2jghcR1vVJn5fqqESu2P
; Wbe9tpIfpMwjE46JjPqIJIDixw/y05uOSSvmN1oTne2QerldDWkHSAWFdjX2oatish9/a+j2dzuTX/
; VQYOXbcHyOw9+cV1UxrgUNfFXlXb1wNH1my25/TNRhQKqUUy2eqj/mC1/4wtofs27tjbfw0UcffU2c
; KEzGCBrWWK95zWsqUOxc3FcxkNEP0uBP1L8oYSIQAC+sIGpdDhI7kxqAMMk7bQNoDdfptA2ARuXNQR
; vHxYvBsUioXLiquy3AFSaT8CD34/prf8y6TbuV/CCZpFF1421P6oN5I430gU1DVYAoLlNRPUQCMBkB
; SpRAdsALaCEikHQcD+kSJZwRAHwvu6g6aY/bsw3njN/TkcD4UGoayIHJ9oyF37TrRTCuXzCxJv3Q1p
; G0aO5wRbIgKf2dfWrzQd2m1Ep+kKQmYMI7AQUH0gSAMQkvG+9OS+aPtogFJjxgi+BRZXOiu56LwEG6
; YHwGNGyn43LcRj9KjpcDzw4oAaqR3qiB+mXaOYYvAcath0sEoAZ3rom/ly9ZmN6/bk51zQCQa2C8qq
; oAlu/qANe63W3jLZv7QfrWVt3ijU6OkbnDQ5Uf5C0757QRI0w8JB+TrqTSMYkBmephCSx8//rXvz7t
; 3LmzOj+gyTvnAbxsW/qdDniI+NZBuRMwGa9g7KTOsk0kVU49dsJb5q1rJvwxyaFC4Kz2QY47HQ8VVP
; jafHAfaIcffvg6aGsfPD6E0SNDP0jWLeuXzE2f3NKXPnZ8d0WSRPWQ3w0o9a0fJzjHlIWUdMmBgpTg
; N8BNnFwOKveRaNFul2/DeAE2v3PeEmhZX/p7LkmNHlDlzdVQrh1/zM9s7Uvrl41VKisvo+iPOd0A14
; c97GE9XXU79FrJD5KJyBtfVSrS5/pBvmVlX2sSS3zoMSLImMB6hcj6aYy2cwzVQz4BLADT8M25ITkc
; j9/HznnYTlMCY4HCFyB0ftMcwbn4m2NGoHocVVWuR9YySju9YTTMn7OqP31tV3d1bzi+/qORUOEYUy
; VU8OTpqtuh0/Bqj8QIKmT0g2SS8sZGLcPHkABRWMjxub2tCcgERd1iIpZUNkACiHj75+qhYGBCqtb5
; HdvGDuDpjC//zWxcgIOgUiRb/rvHRdVFcipdS5KRccBSlsgZ1VBYV8DmfdgwNlCRRvpjYiZhHNEWWB
; Mq99HWyQ8y+g0yOQAbE/PklaPVZNLdKb7tJTWUdk5KJzBSQtuZBurYOQ9qHb/rGlYCk+rqa1/72mq7
; GMiqCsuaD6AwZo6bH4fvAYr2PiVi7HwPkNgmqqHxurS9GVDr/eDevGO8tyJUMB9wPqRdXPtxfdPJj4
; mHT1fdDr6WB4jyxmWC8TbWo8NCGaONCT/IL22fk04+dmKyRPqcCRUnohO9MeldD0D0xlD1AyyCgb81
; htsN0ckBRdcpGVesyhzRPJ5RBIBN84OR4JoQBCtAicdjG1lIxys7qhrqWDRJKIUjYyp7az9xYW/lj0
; mAK/8jmUlgpHEdCctxp0qo1P6YB1kr+UGalIc3O579vJEBk36QV2/qbREjqluqh7k0c1LyuxR7riKa
; fwQyIwcWk17AKEX8zq4LFoDD4M5ajWP5fdzOdRqT3Vg5o7mjZASwRpfnKqhrQo7BZ7xWr9+1Jvu1vF
; qGB6p7h4cK9xIwn3baadW4uW4JlTlz5kyZUKnNB7O8dSqUEQM5mQQwgju3b0vnrZ9fESP4EuZeGvRI
; dMRutLZSKl9vuc5CrWPycqwIkggouupo/E4bHOd53etel84444wKDHyXb8c2/GZAaelcAI3f3SaCjs
; 5xVXkZc74OjWs7U/nFe/am5X3pph3d6cL1c6v1pQRQ9MecKqFCrwNcZ2kr+UHytm0Eh2AmAm95/SCv
; 296bTt26scXGSXxE2lxGTynAhFQ9dLLqb6k04XekZ5RkenaUQEXnGOyn9wifGN3pTnDWmrKSbIPUgo
; QBRO4DuDmWwORvJHGUonwXpa5p9yIAPUYkW3KSSKZTg/prNq5s3tO+6t5yjyGh8oIjHJPg3akSKnXB
; kVnSIEbwSo8PSCdfPSiYGFUyn+AHyaKfxT+/M6mZHAI0Vx+ZXExkJi4TtUR0MKHZH7WvE7AkKiKoYm
; csHAPJiIQwP2XsfId/IyobayTOlR8HsHAeVd6SVHS8RqB7HfHazBZdsiEKPO4t52FtXNVMaN7TS5pr
; urzgSMyzWftjHqQt94M0QDT6QaJqIRkWj81vFcrYvLC/zY7GBOdNDIFSMj6rbumiFYHmmowJzjaSLF
; F6RXDxGxOdzxxMdNUx1btS5+WAiglJUToOY2QbVVoBbleNraIemp/a7eI1CTq+lwDKgcd2gD6u17yv
; x4/1txUc4f7m/pjTKTjy7Gc/+7bafHCAWylAlDdmzKmvTYuJQHAlD/8DG/vT4pHd6w4N0LJxTD4kIZ
; JIFdJ1jxPQyRqZQia2azCZQ8mQkhRTLVXN1FSAJFBqAQKOy1gAFZ3tmdyuL/n79NNPr87lcQAqarPm
; Ccdv/kvJHo4l+NiW/137lYDH+aOBnfEi1Qwz0rgfzQfzhwfTB9d3twJcGUdecITvpirtan/MA9h4u/
; GWy4kRY8mktKtCGSONqsgF6s1pS/tbsWKRqMgZSH5jXyYzE1c6PZdoTDQAgQTNJYi2K8AsJS/QYlfK
; oIZid1M60gEcHQDR2caqp64ZBSHSjjEjHQFyfh7Xh9wXVEj2y8fsOlOTRwl4boP05FxmIYsqZnSUtp
; +2tHePgiNWBHJtOR1ChaXE/e9//9p8sL/aox/96BVRhZTu1w+STyfemgWNavH+iePn7OEHKaPXKDgB
; +/ZGOjIxmBQ5nS/rZ+qDKD2UYnYmuiAQJBFUmCeQbBxHMHF+u1V2lGzxN7dn8uIEDR3PdeXn4dxcM8
; dQ2uVjFnQcl20i0xlth4YWReN+vraTdMn9MS04smpspNIksClGH9a64MgsaSU/SCWGKiT/AxImCL5+
; N+7oSZesa/eKVyKUDNja0KT7VaMAHVLBycc5Vdl8mwOWKMmiRDPGDUkmg6i6CN0vEQOA3cbOeXh5AA
; D/B1xxG6QN33MM9odQ0fan3yfbCET28Roj8KKkq8JzJl8kXjfHNmU790ZyRlteiclUm2iFLQ0OpEvW
; D6ev7ZqoV85vGPdjrhiO25hi9AFLiyc84Qlv7qrbzBve5CViRPWRTyYYk8pCGbCQVAmVxhdI0Q8yGr
; CdfDoURxVS4zPEC1ICoOREiGslyZAozaLUYtICLF4MTLQIHLoqH8fBR1FJHDv7s41eMlxXfhxIF4zl
; 3pcoDR0T59BpOZd4UcVkO1lc7kVUMfVQiaplDjxtkmyvB4wBrtEfk24OF7WJ2h/zADak2hOf+MSz4g
; 1V7Ygxaahk1SRuUtAtP8jB3SwkE4nJUgKbks1JnIPNt7umAyayNq2oOkbiI5dkUQWsylS94Q2VOpUD
; yc7+epUw4UudFwDHEDSlDuDOOeecFqGTq6EAj/Eo7UrA475wfyFyoh2vRKiUQpCi6cD720oT0ZR27x
; ifyBjGs+N6UYtj9aDpFhx5zGMec0JX3e55K/lBGoQp2JhsE36QQ+mC1U0VcvsxadeSvrY8ItEPUnUw
; Tgj9CnUkjgZsJ5cgUBIi6YwCz4kQpYdEh5McAPIGZ40lO6mUEkRMftRHwGTqPG2D/E/3mhmPrlz0CE
; bzZAomCBXGLEkUQacXjOSOoOM6OA8sJH8r7TQflECn+UB/TF9m2h11IsgTIJ22Yijdsqs3/dtx/dU2
; jDUWHFFCTpVQqf0x72HLC2WYD9JcIQZcVhNwbn+1CCe3IpmmVIX09oh+kPoCMml0LjbgMko1JpyTBO
; kQvTiUaryNkSDaynLVUWkGqBgH26JG5pKKtRfH4jzW+pZksQM6QMWngbHxd8aABOIToLFdfh6kIdLD
; 9V9J4nk8toHM0C8zqpka1O/OfOA+uQN0NB/4LKp7NzyRHzP6Y7J21izjOKZDqNQFRzq0ToUyYsgHEw
; S1bsnCBa0A0TccO6ctBZwTXZej/GFzTCVHDjbf3pwHZpDJmYNNqcZ5ABLbxQkc11KMg3oDSK0oyexM
; cEDCeq4qQdwcU94BEpOPNz9/l7YBqBwD4En/2yO4SfIaSZgcfAAa84SsamltZznkkpO095Nr4dpVMf
; Pocmss5JmkY8ERgMh4c3/MqRIq9NofM2u5HyR6e6z0SWfSViQC4f5bmuu1E/vaCmXwIJgIsmIyZBFs
; sXa2tjSJACePb/powC7Z0ZRqAA7gRfaQsSMlAAGTnQmIJMslk+nFq3QOzZcAf6uOuq5kG8ACqPQFjd
; vwHeofx+A3QBelYA48xgqo+M7xsj3rRsDv/xIqAi9nMgVpBJ0eOTpzq01E0EkwaT4w0tznuHpuX/rC
; jqbE2zJYESpcTwxw5VgcY6rSriZUusoBoqYxkBWMhTLwzYOB/Le1PWl0eHdOfX6T7o8uW67bXEtoG4
; phNEwa1SAmtXR/yYCdg00VkonO+owJC7jw/mCiREnDMfiObQEXKiTbRvBwvRyDbXQ1Y5vYefFolOcY
; OUjdht8jwONY+J38mIyDcwBCzRNeF/erZD6IwFP95m9A5Msshv14D/P1XJ68SAlZvTRHh6sYO/0xLT
; gikcM94u/aH3MKrVQoQ/JC4gOD8EUXXVQ9AOh+GK0tY31tyUxNWVDKmiWriRSIhtpclWSS8hBLvo9K
; NtU3wZarkIyBSXzJJZe0SA3VRtdGShJURMERO/txPUggMzyXOm98VGu25f/8OBIuSruSxGO/t7/97e
; m8885rk85xbad90NSBJdDxtxI2Vy1jhIWeKVG1jN0Qo5gfc8tYb7r+xAnmmbTyF154YTUnZuqPeZ8i
; VEp+kKiQUZ/nIaFK8R2Zs24+dSR9eFNftbiOqRF4SLJhMQmOD1XDr2qI9iAfFMeQNo9MXGnNBtBkLJ
; 2YEWyABKkEUCAokCIRaEwmJDWfSB/tbBFIfIfUUjVkIvN37PyuFOST7eIxIvA0nPN9BB77MF7NC296
; 05tafpteW24+0O8zgk6DvtnALCIZQed6UbIkmmdczzEm3bvy+gnzmmrlJ7cONufAcFq/aCLtAy8tt1
; FC1gVHCi0vlMGbSVcqbTQ8IMCGHySLZ9SK1y3rbyXNiYlV83TirttiYtVIUcd1m3k/SiE0+botGrGj
; AVsvDlRI3bxMzIMXCROD7xk3YIySTIC5NmXic41S/XTURfbjHGyHZOS7uI3AzMEbwcc2Rg+wtlSFjN
; IODxXGWTIfRA8VzSHun4f+GOAa13PRPsczMI5O8knwRXLENBe+ME5f2pu+vGOCUGFfrmNfBLgesgVH
; SgGieT5IJlcVUBkKZcTyTzzwt7zlLdXDj+xWVE14EzMp40OOqqQhJTzE6BsZVSTB6PqupEbyO5IMUM
; k+5uojkwI1iBdIBBpdicU1A07pfzr3IHbUKHr+fdxeYHrcHHiAm9JZOg7naqZlk3l56L0Sged9MI16
; HvYTfS/ZhnuspMt9Lk1cmy8F4jNlbrAuju57zAX9MS04wlrffRuTAa73aX/MEt1vLFX0nzM13BkrG+
; nGne2FMnwATAoelmRBBFvMr2jujegnaVwbky+6YzlZ8oBQQ2h8qws41SjAFpnFHGy6g/GGRnow0SPQ
; AArX4UtGB2XBxHGZtIBWgzjAtRpOCXiASmkXgcc4ABLH4Fi6j5VAx7Gh47m2XL10/GoBqojxHhqDp7
; SLyZUaISenJp88MZExjIw1EiqtOg7NOXH+yt0FR0y2FIE5kwDXphZ28EaWlwJEnbTeXB4+k0g/SNyz
; tiwabKOTVQ+jRFOCxADQaGSN67aYFi7a3Dim3igloiRft1kXDpXMCarHh/S+dD8TW6nGJIXkEKQCic
; 8IMACjpOIYgFRQ6xfJ94DK79zX47gNn3Skp4UYlXZsz4SOoIvmA9ekSDyun+8Yq/fKe2OEg6q467lo
; m+P3yFK6ps4N4WofxjBGaaezdJSC+mMyZzAfcE+4pjg/2Geq/pj0o48++uAiVUqFMvToj4GHTDoenI
; Uy3n1cT+UH6TY+xGiniR3AuPYoGbk1GTCRY6R2nsjH9Ulub4uqpFHWGo6jEZt9GachPUzuqEIqbQDC
; +eefXwEvAi0CiuPzO2s6QZN3JhdSy7VZPEZUQzG6a8eLaqZj065Xstlxjdw3jsFYomoZ7XPcO8GbZx
; RTpWRbnlHMRp0bwxk7AI+ESb5sEJgt4qz5kr7iuImCI1sWTaQ95MXGNcUU7ngr7Q1gL3/5y/f47gUv
; eAFeKrOfVHnIQx7y/LxQhjc/rsV4AIvHFqSLxwf3KJRhOjvfjKbQjr9r6OY3Jh6TvZHlI5HOj2/aHH
; CuQYyWdru4duP4rCdUBaPXiJOV66Ez+QBBDjYmFC8YAIADM5JH9TACiUkHEEwgxDaxu60qq+5cAo9t
; mHQcn+OpspZAp/mAnquW2us4Ji81WeMYY6c3jdqDuVwi4IyiMLIgZkHzWXHfGE9MTMSxOO/73ve+9J
; GPfCRde+216YYbbkhf/epX0ze+8Y30rW99K91xxx3pRz/6UfrJbZ9Pt58xN/3vq95SmTm4Lxwv+mMO
; 300F16Ymhlq5BxCf+MQnzl4vlSOOOKLNDxK6XyZLYkR/QHzmIEY+dnxPWrt4Qn1UfTDXY3y76b3gmi
; +vWgMweKtr3Fb9iXY31205MxlVSSeeKfAAAGDWg4Tries2/SB1RtatKa6lAAVSIqqAHFcJxIQHjEot
; O8eQvcyBZwdQnF9VEoqfY0Vp54sgB5yg43t+95qiA7S0PmMDxN5XXya5mcD1Gz1PuqQhXFCxLdendx
; Dnu/TSS9PXv/719Nvf/jb985//THfX/vWvf6Xf/OY36df///+l//ueXem6k4YrQoVr49i+qF0e7I1Q
; ac7d9JKXvKQNhE1Jlx75yEeu6JpNrZMfpEDTv46HxttGP8gzl3W3LXT16CipFNreeMgeNzd0cx5Ahz
; SK6b2j7S2u2yLgojrJg2GyS/dHly2lmyV5mczRyyOu2/gNFpPPXIXUGRnQwbxa9FBPktiZOEZa5519
; AAfSABaS40Q10/NqVukEOt3LuKbo+xn9LtkWQPOyKPlbqin40tGRPDeE8x3XZB2FK6+8Mn33u99Nf/
; rTnyoA5YDyM/7997//Pf3+97+vgPmPf/yjtf0t7z+v5Y/JeVi/xhJcakt7Uy8B2vOe97wKgH735Cc/
; eXZIuib62+h+cg6qNggUVaHli8fSe9dPBIiuGunZzTxNEiM+wJwiFmw8fFXMGL4v4PR9ZPKYmq3kWa
; KDsjajHHBMboCi975gE3B8FwGgXS6u25Raqpo52Oi8gJgQSA68VGQq8w5Y+E1pF3/j2IANNZLjSbrk
; oJPYsbRVrlq6xvRZGUbkdQs4VVa1idwDRSO7S4IccLppMeYf/OAH6Xe/+1364x//mP7whz9Un3feeW
; cFJMHEJ9vQ/ZvPn/70p+lvf/vbHhLvS1/6UtrQJFSu2zonfWBDb1qzbEkr1Cg6Vhx0Aa4lP0hAxsNT
; jFsoowrgnAwQffe6vrRowfw2yWZ1lug5EBfHPtioYroGi6nJY4o7jgtomGyliAAp6ZiyjonFZDLdN6
; DUKViwaTtT/dJHUsOyrldMXul61T2345OxmTpOKYakYyJHUPG3HUkGKcPx+R9Jg1TjHivtSoRKNB1o
; PtCgzJiVfvGa2DfG62m7lDzhmIb8cO8kltQc9GM1ho5nwLm5D/zN8QDPdBsA/fOf/7zH97fddtuEPX
; bJ4vSOdQPphh0T5gPGAtDVjpgzXPt0Co4ccH/Mkh9kJEYADDefBzsSCmVsH+tuSTQejMxgSX2U6DCm
; qsRaud6LJXajcdUHy8RUvYnsZAw3YfLzQCQGoqHbTFWqfZIlMYRGWxrA0Uk5GrH1GgFojEeARGkFWF
; DZsIMJqlJHcqKKQr5Ih0cVk09dwHLV0nWl0g4AG0+Xmwlc2xl/mBvCDZfiJWFUffQ88V7zsuI8TPBY
; ywBw5CrkPW1IN0CXt+9973stso15sn1hT6vgCElqXQbIASiBp2o6wB/zgGQMKxXKiEZHJrueFfhBQt
; l+eGNPm8eIAaIap0uAU+JIJee/a+jmd20/OeAEHeoNdiVzlkTAMXbXWbKUEXCGq6iqMWEj4GKYDJIF
; AJS8RmQpJUdywCnV+GQCn3vuudW25vuwM3FRPy3wwfmiRIxsppI2B5yGZV4OjtfriIBzPOxvOE8OOM
; 7FcVjvykJGwGkv9beYdAhVuqQW3pPGuu1Xv/rVHt//+Mc/btn6Wo4VjYkAV5YyW1eOtWL14lxivPe0
; 4AhrOtZ4D3rQg/afd8oDH/jAI0F1lGq80bjZkcqvPEZGhlvEyBtXDbVdXO4HqV4fXbxMJBPtbdHw7X
; ouBpkare3DzAkT9mdsTHaPx2Rg4gpcJpFqlIDj4UQSIUZYm5Zc1dB1kdIqEhaAg09VSr1M8rWaHaCQ
; kwS1jWPRmaBIPw3r9JxQKZkPOFc0svO/qRrMiylL6TVJ1ccAVt3dTCOhCunLkfFJlnB/HadSRB9W0z
; CwH9T+dBqS8Re/+MUe3//sZz9rkWP5nDnvuNHKH/OC9XPTBz/4wWp88SVuIqO9gQ0ipYmD9IQnPOGO
; /SbhOvlB6pFvoXVzUSC+Wa8p1XRYtQhGST00RbflfPNttM3ovlUKxRG80Z0ojw5gDExi1DrGXPIuMV
; TE+LbIUCrdVJl5aNGYLEPJJNZbBJBHsiRS+hIh+VrNDuOKsZxuzJ3d7eNxSjY71UeAxnXrc5kbwn1R
; sG20yUmaeF9c/8XkQ95HzsE4eZFZDHI0q1lgzCHP57LLLpu2WvnLX/5yj+8gWhhvnDOy0ny3bXxZ+j
; 9v3ZDed+JEuj9TDHotrv9L0g4TwVOe8pS7Hv3oR+8fh+dSoQw6gxE4DI6HDegE3FvX9Kb/vnUiP4Xq
; oSpkJ68RJ3XMyhW7YRwuwkuAi5HdnRhKXxB4jTC5SoBjAmpHU5XKAcfvSpY8CkDAIdVU20qAk9KPRE
; gOONZIOEDT+bsEOLvHKQEOIGh41xCeA47fNCuUAGcSI1XMEuAcMypmKVwn+rWOTRYn+fnPf56m02A0
; c1sdBnE1Kj4ldXgJE6t46ubx9M1zlqerdk2sy6+77rqWucoXNQCM4T6okM961rMwgv/kIQ95yP7xPs
; n9IEudmxnp1mhsJD/FzTvmpPOPG20Dkest/zdmSp3bmKiogyv94j58l8e/xTWcmYJj6jsmilV09FCx
; tK8qpV4iqpRORgHHBOGapb9l+QwG1WjMQ1SFi2pdDjpVQdXdKLWgzqNKCUkCK2l2aXtUSzWEey6+cy
; 3oeDhWVIFlUc2rIv3P3wLO46lSmllMwPEdpBPHc32sWUSnhTxywBp0N91007SkHKQJtjsbrKfzUU8Y
; /uZFdNm73pG+8M4z0+2vH00fP3dXuuqqqyoPFl48zivGyz5xjr/4xS8mhCcdccQRNz3gAQ94ete+bq
; UA0b11SJMIoJgrcsuy+elzW7sn64X177FuU5SXJJq0vXXWSqRJLB7RiaXUs0Fv/Zw0YTKZm59JZfGM
; SJrwttdtyvz9OWmitNLdKidNouNxCXDmJuGhc/8gRswzEjuTGkJFF7BIuLiGk8Cxnhzny0kTTQiymT
; lpQncfzSAl0sSUDmZQzkkTJjTqpRmb81Adnhkax1/+8pc01XbXXXdVUo4GicK6zBg74+NQxT955eXp
; xjcsS7e+fix96D2Xpuuvv766R3FJI2sZpVqTiU9PetKT7nrYwx52Qtf+ak2R+XIt7Pe0Q6B4A7WbIU
; l42xAFcMma3fkp1K1V1aK9LQec3gwlNTRWwFHalVhKI4RjerfcLACY9KrPWUrNAkxO0x6UzAKykNF3
; MWcp41oqBxzdaHHscYbllDrnAJBIPINYc9KEa+Z6NHSXzAK8hFQxS2YB16GmSs/NAnyaMsJqQTngJL
; MAHecupUZnP+j8qTZAxpqN9u1vf7uVEsLlw9VXX52uOHNn+p/nrEhfuWRXuvC8t6Rbb721dX75BeZY
; TNOAe5fEyH6RarE12cinH3300XeyQJyqbQIAMCEFkV4FPARSj1cRAU3D96qli9skYr5u48bxEFq0bh
; YTlYPO+DdVFAHnesQsXTomCzr+ZlKZs4OxI+2iSskDjCxlnoHLdY0EiypljN6OoMsdj6PdDAaSiSmo
; mMiltZpSjbUSTGZu+NbO57k0DTgezQWu32L+E69J7xivm/34TcCxn9m/VMe1q5YKgfAMjFqPDgoCkv
; t+yy23pB/+8Ifp17/+dWUuuDtfSv0o8Tzhvsl28/JcunhR+sTJi9LX37goffqyi9K73/3uifw4k8wl
; 5zbiP87h5z//+bhxQYxcfsAiwQFd86Tfffazn72HB/XddVy7VPMEhW/J1cuWpKs27K4XlquH+jmW7G
; 6lmKicOInuWYb+5MSJKck17OauXfxmLJguUCXXLj399SgpuXYpXQRd7trFvgANlQqDd+4vmRMqJbcv
; 9sEIDviUNrlrl5KV43FfdEeLrl2ylI4rrt8iaeI6nfOUclfGDM2lpEI8E8DBdvpo5kmF9L1lO4iOj3
; 70o5Vk+v73v1/Z3v76179WYARwEC5XXHFFKxER6973v/Xs9L/OXpquPWVx2rl5fWVgjy/sTsTIM5/5
; zEqqPfjBDx7uOtANdD/mMY+5FNH6whe+sKMBcG/STraIi2XCIO347rRjeyuXG+qFeRNijpGSihmBGR
; PI5EylLk9xvZA7L6tWxQo4eZJXJjAPL883KVOpwdeksrnzMl1pkkdyCzqkEVINsEVpVwIV5+rkvMxx
; CEsBeIbr5B4mrv+iA3PuvMxvJjrKGUrXskgPxqOvZO68HDM0d2Io+VvTjEHDedQ3+zKOuH6vKvA0X8
; aAhRfH2972tnTxxRdX2zCmy971zvTFS05LN5/Uky7YfGxFirCu0ylCrYsxxbmKszLECHT/vV5vrrmm
; 62naHn7CAnKqoCM8RxLCNwtv4SrsI+Sn2LB8UUsNlVDpZD5wfWeSGTs30Rz6vkm19cQ03EYbxGSmUc
; qZ7cqIZuhtszALOEkRE7rmDswxYsDMWXnEgNmyXM/pctQpDMcQH4FpZz/uKX9z/YAuD8/RA8Z1pUZ5
; wWZZZoNRVZsj4Mxf6fO05kGeOq+UUCh3XtZdj09eAnmaBVV/X9aagaJN1ko8HJeQnvdefE66/eJN6V
; NNgm58yfx0++23V+OPyxKuNZdqz3nOc/Y/MTLVNslcXtNpXcfAOwHPzFzR20Rvh4VjC9JF44Ppa7u6
; 9whA7bRuyw3hPjidYvNobyO9JQJyB2YNozrkaliPxAkTnTWG4IlBmrEGgHFypWhv1U/2R2XFOGyAZw
; xAjZR+CXjRQ0UH6KhC8j1j5UXB8azEkwegRiBzjFIAqqDU/hezeKmaA7yYPDdfv3kfLVdlLFwjFG9E
; PVWa5bGQajam3OCZ6hzh/fgfn3hX+squ/vTx08fTl2+4IX32s59tMyPpeJETI02uYv/R/TNtrOtQL1
; 3XOXgGfk8IFqRdTPJqhmIeVqwXRh7CSKh0cm72QTChTDhTssex/5bJKjCdUixYuUbypJRigUkBHc9D
; LqVYyL0wSqBjHJAcSIpOKRaUVDGSO+/8brqHTikW+P2CCy5oqZAlQ7deMPxfSrHAsVGrGVOnFAs6NV
; gnrlOKBZ0MGh1SLPAy4lydfGvZzmgF/mfb//j8delrb9+Zbj19QbrpU1e2iLbIH6hdReGAHyTEyCMf
; +cgLumZzaw5wFwwmi0v0Xnqn9V2pE3/kA1JlVI3CfGC9MM0H3rQ8Oai6uH6RPtRGlpxGckQVUz++GD
; VghRyjyGOhe6OEjRAwN7+L/hx0ruVcs0XVkheDmbOYyEiVCJAIGrrpEXKwCRLJDZ2Lo71PYoRxYzrI
; kwgpGTR06+oVaxCwD+dSlZY8KnmX7K2yji8nn4Ggi8/J/TgO67oYruWLl7FpLGe7MzYcm776+gXpm+
; 97U1qzYmkrTCna1Th3VCGjH2STGOnpOhiaDCYDf9rTnjYlwJUIFToPkgnJjT1lyYTTM/6YpXUbf2uE
; jsSJhAoPO7r0RJtcTN3GtkwiJkC0yUmaaNQ1Ni4awpnMkB3mNynlpGSMSiCIBpMLxTR5evqX8lF6jc
; bRqUKqhkYyxPUhn9ZkiOdiEgM8gcY58zR5OjGzL4QGn3maPNdtJcB5D60fEFMSRmN3TARbqgnBM3XN
; yzY8r6genv7a16TbP3RBuqVJjFx+xtbK1gbY4prfuuxxzjFP96sf5P5sMpjNN8VtRx111B3TMR+QWy
; KqD9wwc+7n9cLiuk5XrJJpwESwTPK7SwTLRNxbIli96TslgmXyobYx5k6gY/JjoLYoRykRLGMRMJ0S
; wSJt9pYIlutlTYhE7JQIFuDC6O0tESxrVVS16FWSJ4I18jvmpCwlguXFsLdEsJIy+fPzufIbDgASH4
; wLYoQ5ce32Rrrh369tmQPiup7xHXA/yAPZAN9jH/vYy5/xjGdUfmdTAZ0eKlHambhUf0zzU2hgtkBH
; ThcLNm1vMQykEVKdM5lkJHk4ueeJoShGK7s+ySvmmKmKsSI9YqVSJiQgQbJIUBgRngOPrnSKcXSmRN
; D4bXRBHr2tMVlp5xoy0v5bJlOt8x3jggSJqdkZO1LYFIDul4OttG7LmUnz0ph+0NwyjZDq3KgRX3A5
; 2PSD5FlXSX/H16Sz146k204dTDdedlb6zne+kz784Q+3MnPJQDOuOL/gF/arH+S92Zq06ormxf2cBe
; neTAWljj9mZCR5KExWHvba+QPpS6cMp49va7QRKjowaxKwVFIkT5wcjckMUUyuPFwnBrEa/5VHECgB
; SqCjA9CYwAcprM+l0iQW1sgr5sQ4OnNF6g8Z1UPVUNdcevfHY8SSV3RDg6JU04VMlhKw5RV0uC9mWV
; 7UoQa4a17ApfeJ9faiKcZ1mxIzkiWyzY0OSX8xH129aSIPznUf+0DlMRLnimaEmBhIP0iIkVlF9+/r
; htGwKbpvglSZrj9m1MUhJzDoLpg7Wq3pzE8Rb7a2o1w18aHy8JjISr5SyI6TUOCVsjCbXzGWcoqg4z
; ccZfdWrkpCJZoPSuWqkEBKpFJnrIBaT5j8OHqDsObLHZJjAQ/Git0uen3kaqR5TkrrNu+TWaY7lati
; P647r5yTLwW49vj8Yz3A4cGBVmBuzmLj3VQiRg45qdapwWY2CZW7puOPSVIXJA8PiLc1Dx1pB3CoF0
; Z+CnKkzB1utBIHWf87BxwTQqkWDeERdK6/XMDnkyl6oUgcuJB3cjLZDMJlUrBuM2Ysgi6aD4wazyue
; KtUkXHIgGfQaS17lBRl1EfM8OdhMAGRCJMCrClmi/7W35R4l+p/qEqe9La8NF58BIMkBF5P+Vp4gjc
; G2eoCGgSkNuT7rs8e5c6/4Qc6WNhN/TAox8PCiPQVdvqqI2lQrrzlhIN1wUn8an192+4oPMdLP0tf5
; ei7a5nzL58UZo31Of0q2Y2IbjhRdoDABGKVQstkZ0mNcneE3eUXUWKNAJ+S4jeYCjqFDgXa1aJQ3dY
; SlkPN8kxaBzMGWr9usJeDaLy857LpNQ3durhGocSkQ1/Ar5w6k63f0pas29lTkmS8Z54KByLltDa0K
; YuRe8YOcLW0mhIrmgxi+w6SBGWRCxHph0XxgHpJ8PSfoDKs3tXYphZ5vZd/mpdyVPHRUP/0KcxWTCW
; 0QqWtDQRfBZ1YxxuQ6K3au2ZoFMYQmdsBoQqEoyaIhG9CxzjTmL1chzUcjGEtrNgHFeSScSk7KhvZI
; WuVGbkDjUsDnhspoPUC8jqyKE2vAOZY4R/SDbLLmZNE6sqtu7f6Y0yFUpJx1iGVyVV7sWb0w1Z8YER
; 67bmDRsJ2DTuDJWJYq6zDBkRQmirWKTFQzYx05WEzAp7SLrlOaDFQxo2SSmdWQriSL25hq3drhrh/j
; uVDHMBuotvJdqeiivqasnfM05rFCjoHBageliqdsr70tfwaMm2fK/hVxNdrfVg+QcfEic42m6h9zSM
; 5aP8jZ0iKhEvO331NCRdXEt53eGkPNN+NFq3vTLbt6067lu13HZCn1FNeFK6eorb5aknbsIxNnSj3X
; UHwvcCVN4gSOTKaVgszNT9fgnQNQjw/pfEAS6XvVQ/7X/zICzDTj/i8BEyWaHiYl9dGXltnA9JNUSk
; d7m/ubkcsKOtEUE9dtAnUoVDw9Y+VQpUJevLonDU0avWPaA5nkmCWZ+YPTRZPuv+0+Q4xMtz3iEY84
; AfcwzAfTIVSiiskDZK1UkQNjA231wlyQG44jdRz9LJ0UeqeXJJ2EjEmBSjF0MduXDrolicc4YAV1Xz
; LWLMbaASZzm0QpFbv2OQFbOg5gQf3meHEMjkt7m9deUiEBLtIOwOrFE1VIw524J5wnvsyiZPNYMdta
; rAe4eWF/de9M2BvtcXkdAImRWe8HOZsahMqRRx5523QIFd50RgxrYNXncHSoP71/3US9MGrOuZ5wXW
; Y0QQ46CRWOp3oUQSd7aMq8vFpqXghEciECj24Etukc4lrKqqKmcbBKaQ4mU6lHSZYfx0BUTQZxDNGI
; Le2v03a8JourMGbj/vL1Gp+mipdMycGm5IsuXbEe4NzBvlaGZ1V5jpt7jDBP7tUA0UOhPepRjzp9bw
; Gue+vRt7IykDYnIxONiXDqsX1VEOLlm0fb6GeBUooq0FQQMwQzCQFzxY6GfPklQiU3H1gEJDpAxwSz
; TDDWdkogPVIicIzE9n/XcnEbyRape8DMdwLMdVfMveg47Zbh8pr4zmOoWgs8X1yx9p6SzUSvAk4Vth
; XJPTSY3raukW6ZJEY4Tl7x1PsfnzXzwwDR+xzdv6/bTAiV3B+TB41awrpm1cLR9PFNPZOEykBb+L6m
; gZJ6qe1Ib3ylXh7WI3hym11uLNddS8kSuwGu2sFKaqhgzfP7R/UQcPOywRYosPIeA0Zz1TGvjcdYdJ
; +LUg0AmfLBQN9cjdThWF9V7/uqeQOT9QC708oFw63SWK7L3a/kB9nUhu6siZF92DQfoDJMxx9T6aSL
; kQXredBQzfhjvrn5mec/MZVanCxMElPN6WbUaW1nSEpuszPqQKO0KmZOThg9ziQGeDFFn13n5Eh0RP
; WQfSBGJBu0P5bsaJI7JY8Ruu5gEknxmg2LkVk1LXi+ZmNM0T2O+/2G5f2teoD8LzMrA+n9ygNED1k/
; yNnSHv7wh6+TUJmqtMNYboprw3nMlUiAK4tzAlznD+9WMVUR42TJ396qYXdnPhDA0ueRVpedc62kaU
; Gve9UzvD8gRGQK9RJRSuVEh25g2s1Ud2O98k6STOmsGmiokiSRWZO9bp21Y/pBa3/70vK83t+Fo430
; gU1D6fOT9QAZH2thtRIT/7BvlGoGiDbnw66uuu3f1nybHTldf0wJleiPZ9ZiWDH8MW/c0ZO2LepvTQ
; rJF+PXclrbOLpIqJSM5dHuFgMqo+TTNcwMxvlaiomP+QCbmYUycmkl0WFCoNKaTBVSx+Fcknk9+odG
; F7n4QlE9ZZs8rs01m+5slqLyvm6brAeIGx613HXsjn6QjP0+7wc5WxqEynT9MY0miAGJrO2qApHWCx
; vvqxbxTBrz5eeuYLFLqMSkOBF4THTdrgxqzWuJM7Gl8iMYovQxvR4JhnJJZQIe1nwcJ1cPI7j0DS2F
; 0JjVmvG6XisV3WCMnIdjdKL8dfwGeBXZNNReD9CinEZl6HaX+0HynI866qiDM0D0UGkPetCDnj9df0
; wIlRjGweTgwVeeEpP1wj63rS+9bvPaVgYwVcgSoaLEi4mJoneFCYokF6xroNopUyj4ZBBjBjFBr5cG
; JAjgE0i8GFDjIpuoyhmlV+yuqaLB2rWcEi0asKN7luSSRJNrNu6Ntd/MQcqYTt+2sWnE7p2sBzjhim
; cMo36QpcxZBojWdP8saDP1x8ylncGhSJIL1s9LN+1oJ1ScPPMni6+XJJ7qlqnXXPxHqSdJoWdHnPAy
; nW6j4TiXiByfdRxUv0GjJWDpzRK/y8/lOs+ik7k0E/SMSTDmLxylcCwrJt0vMXLuhgWtdO7RD9J7Gp
; +NfpDN5/vFWoWcZe2www4bnqk/Jg+eN7kBmNUaZrSvKq01UXBkoC3PZe4LGCcfvyGRlAJ52A9d38Xo
; c5h7sKgaRokYgaNvI+s6jtUJVBIzJTrfazHjWBxjHLspzaMBO14/2+g/yvfcJ+4Z9+7fT5ioB8j94O
; UA82p5MqvYRKlW+0EeBG2m/phMAIzHhoNo34oFRyKhEhMT5VmmZDc1D2gAtvaZEksjsdvEbFZIrAg+
; VU5BZ3Yu/2eskCql3P0CWR/P+H0snBL9Rx2vaQ8EWsnxOGZbUws4ZXmjChC9ZE135QdpDJ7qI+s6Xi
; YlP8jHP/7x362l2kHSTNeHX91UVUylV/THzAuOsOjPzQfS/jpA51LPdZTqXZQcTmrXbFL7uRoqeJmk
; kDwxrZ8dsEOa8JnbyeyCV5U3VoSNxn0ZTen+XJp5fl8wUYXUD3LniomXhWvL6DHSqVBGkxC7tKtuB1
; fb1wVHqmQ1xHAFf0wCXGMKANS76I8ZO9+b/ryUMcxJDoUu65eroHQr5yil8t9db+nxkf8W1UOkYw62
; OC7Ts8cXSOy6dBkMXGU71kl8fE6TfOqrrhmp60tMZ/DaD/IQbPek4MjdSbtIqDBJcZGKBUfOXd3fki
; aRUIlqpxR8lHY56aBap/1KCScQOIYVOPnfdVdJOglUUztEG5lR1CZP0oujkTlqx1ClqDZ7XdoVZW+X
; LBqr7oVp6fnO4NuYrJXjlIiRWVEoo277ps3EHzPWK/cNzcSv4tOOXZA+fULvHv6YSqvGpP+f9qUoHa
; TtTeUQDeqNECumycDaCI3GnhVcBVSUmBE8vCSQNHqa5DYzbWp6jMRQJUGm2mwdhugHSdoDiJFrNvel
; NYtGW+E/jcbuMtF8l9P9aB81MXKINqTdEUcccdVM/DElU5hkrElY2zUGB9K5K3qqN/sZy/raAiNRt/
; LkRVHy6by8NzUUsKBG5hR8I/Pv1L2s9DvfM1b8MTudi5eK6mEpa5bp5hyv18k1I+kvXNXbUr2xramO
; H5SFMuq271r0x5yqiknBEcNVDOdBZbPgiP6YK5YsbBWJYCLnoGtM+hWqepp+LwLAqGrZQiVQCSySM3
; qwxO9lGFVBjbOL28TEqrKmEXRKKEmPKhX8gnkVMQILuaFJJsVaDl6TKmeUagdNoYy67bsGoYL5AJVm
; qv6YECqCI/pjQnnPG2mk920Z7VhwRBUQtS6XInGiW4DDbWJktPF6uYoaJZWJVQ3lyRP0QKYwZk0Ygi
; SPljBi20IZMR8kL5f3Ht9cbw4PVfY/azn4kuGlhH3T+3ZQFsqo275tMwlwdfJGDxXLKe1a3FdlDIsF
; R0xKC6Ufs4jlHiwYsKOXRt5db2lYLnUmPCDICxnGzu+Uxop0vmpgvCbThZs56/ym6njD9mPSjoU91b
; VidI/ZtZTE8V4d1IUy6rZvG4TKTAqOGH6jKgcdX4XVNClxC46MLxxuIyvMGBYnN8QIks08K6W1XwSo
; hEu+DfupHmoQz7fRyx9gWEI4jsXMWaqwnGv1gqHqWrgmPEb4HUkZ1dBSXexDqlBG3fZNm4k/Jl4S2s
; OiZLDgyPnr56VbT9ozP6YuVjl9Hp2ppe7j97HrkxlJmJhWwkhpPURMJxePyb6MlxeF7GocC1INYoSU
; FG9eNXEe81tGP0j2i/elDhCt2902/TH3RcERJjk14lAhV4/2ps9t7a6kw8LhgbbEtahkEax51xm50+
; +Vv2ITaBwrl5pxG9MjdDoOoCFjGGtHv6sKZTTHDDGycqS3Og9eLPqdylzmfpD3iUIZdds3baYFR/Sk
; cB2GI3QMcNUfk++RLKqHcT2Yd3PqlwBl6EyeNClKSsaiFFbFjNvwnR4wkD+VN//iUChjaMKvFDDKzh
; rwmtP9dYBo3abV9MecToCrtjEnNBNTf8xdK+elr5w8mC7fOFipa9FutzdJphSKLlL6OEb1MQLTkJoI
; MNeI7meOkxa4m+C6cstwuvnU4XTKqvktJ+noB6nPZ7zm+3ShjLrtmzYTf0wDXCPZQdUcUt/Nb6qVqG
; qYD9bO62+TRnkG6dK6zVptewOm5Xw7bQMwYSrbC2VM5IPEV3Tx6GClEjNmr6HkB2mhjNoPsm77pEV/
; TPz+pmM+YHLjgWH+D1zDAFWngiMGkHZarxnoWVJD9d43gDVXH1VD6RIqlPaKhTL4Hgdpk8vqw9kpQP
; Twww+/pvaDrNs+bTPxx9QLJK7JLFWVFxzJ120CxsjtCCADTf3fpEIRoOZYUeXUgbgl1eYNpE+d0Jf+
; 25buyh+Uc8CaCmakLi8J/o9SrQ4Qrdt+b7zFm6rTF6frj6lvo5MdEoLJTcGR81d2VxImeqioHpoMqK
; QaNiazirFNJ7YTgFnQIwJWP8iLVvWkkaaUs8Ze3K9EjEz6QdaFMup2YNpM/TGjKgigIFSqjFwL+lsF
; RygsaX5HXbo6rdeQSuaM7KSGKv2qiILBgZYfJHn82Vc/SHNNmv6gRIzUfpB1O+AtFhyZbn7MKG3My0
; iA6xXHHZP+88SedPLqBW2ESjSEsy9Aiyqlvpoe1xi0KFUp2cWxiVrnXONNiYYpIK4B2Sf6QUIYBT/I
; 4a661e3eavvSHxMAEX1QFd1YPlipmNEfM67lrKNWkmgxe3JrTTjpB3nLzjnp9OUTxU2QanGbTn6Qda
; GMus2qJqECkTCTgiPmPIFQqeoEDPeHgiMTazsLdRhZkANOP0iDV6X7ox8kEgwWUoA17qZQxkMf+tB1
; XXWr22xqM/HHhJRwLSZwiCzQH9OCIxeun9smEc2IHG1rkclk37PWDLcKZegHGSMWTJVQF8qo20HZZl
; JwJPfHtOBIVV546bx03dY5VYArhEpct5k6oa06aNO4zrYQI8eNTQS85oUykHCdAkTrQhl1O2jaTAuO
; WPPayG+Agu+l/phQ+ZoP9IM0BTvfbQ2FMtgHMobQH+165iepC2XU7ZBq+GNOt+AIwCACQPUQQOUFR/
; DHXLp4t6F7bN7c9J71A+n67d3phLHealtsa9EYTtxdnjmrLpRRt0Om7Wt/TKQdnvvjy5e0/DHPWdlX
; df6+ckN3Gl8yUTwxJvMxL0pdKKNuh3zblwVHkFaol/pjrpvXBNyKnnTWit50/Pzelh8kjsmu1zScx2
; PWhTLqdsi3mfhjQqiYv1IAYj6IVV1Z75m/UiM2+/B3lGq1H2Td7jNtpgVHzIsiyCBEAFkslCGZggpZ
; KpRR+0HOnvZfXSccHmGaoYAAAAAASUVORK5CYII=
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.40mm
; first layer extrusion width = 0.40mm

M73 P0 R4
M107 ; disable fan
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M204 S1250 T1250
M104 S225 ; set extruder temp
M140 S65 ; set bed temp
G28 ; home all
G1 Y1.0 Z0.3 F1000 ; move print head up
M190 S65 ; wait for bed temp
M109 S225 ; wait for extruder temp
G92 E0.0
; initial load
G1 X205.0 E19 F1000
G1 Y1.6
M73 P4 R4
G1 X5.0 E19 F1000
G92 E0.0
; intro line
G1 Y2.0 Z0.2 F1000
M73 P8 R4
G1 X65.0 E9.0 F1000
G1 X105.0 E12.5 F1000
G92 E0.0
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107 ; disable fan
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2
M73 P10 R4
G1 E-10 F43200 ; retract
M73 P11 R4
G1 Z.5 F7800 ; lift Z
;AFTER_LAYER_CHANGE
;0.2
G1 X4.847 Y5.243 ; move to first skirt point
G1 Z.2 ; restore layer Z
G1 E10.2 F12000 ;  ; unretract
;TYPE:Skirt/Brim
;WIDTH:0.4
G1 F1200
G1 X5.992 Y4.186 E.04626 ; skirt
G1 X6.588 Y3.739 E.02211 ; skirt
G1 X7.351 Y3.249 E.02693 ; skirt
G1 X8.829 Y2.515 E.04901 ; skirt
G1 X9.527 Y2.255 E.02211 ; skirt
G1 X11.125 Y1.841 E.04901 ; skirt
G1 X13.219 Y1.643 E.06245 ; skirt
G1 X199.554 Y1.667 E5.53253 ; skirt
G1 X201.166 Y1.905 E.04839 ; skirt
M73 P15 R3
G1 X202.713 Y2.419 E.04839 ; skirt
G1 X204.575 Y3.494 E.06383 ; skirt
G1 X205.793 Y4.577 E.04839 ; skirt
G1 X206.806 Y5.854 E.04839 ; skirt
G1 X207.581 Y7.287 E.04838 ; skirt
G1 X208.095 Y8.834 E.04839 ; skirt
G1 X208.287 Y9.925 E.0329 ; skirt
G1 X208.357 Y11 E.03199 ; skirt
G1 X208.357 Y199 E5.58196 ; skirt
G1 X208.287 Y200.075 E.03199 ; skirt
M73 P18 R3
G1 X208.095 Y201.166 E.0329 ; skirt
G1 X207.581 Y202.713 E.04839 ; skirt
G1 X206.806 Y204.146 E.04838 ; skirt
G1 X205.793 Y205.423 E.04839 ; skirt
G1 X204.575 Y206.506 E.04839 ; skirt
G1 X202.713 Y207.581 E.06383 ; skirt
G1 X201.166 Y208.095 E.04839 ; skirt
M73 P19 R3
G1 X200.075 Y208.287 E.0329 ; skirt
G1 X199 Y208.357 E.03199 ; skirt
G1 X11 Y208.357 E5.58196 ; skirt
G1 X9.925 Y208.287 E.03199 ; skirt
M73 P22 R3
G1 X8.834 Y208.095 E.0329 ; skirt
G1 X7.287 Y207.581 E.04839 ; skirt
G1 X5.854 Y206.806 E.04838 ; skirt
G1 X4.577 Y205.793 E.04839 ; skirt
G1 X3.494 Y204.575 E.04839 ; skirt
G1 X2.419 Y202.713 E.06383 ; skirt
G1 X1.905 Y201.166 E.04839 ; skirt
G1 X1.713 Y200.075 E.0329 ; skirt
G1 X1.643 Y199 E.03199 ; skirt
G1 X1.643 Y13.219 E5.51608 ; skirt
G1 X1.841 Y11.125 E.06245 ; skirt
M73 P26 R3
G1 X2.255 Y9.527 E.04901 ; skirt
G1 X2.515 Y8.829 E.02211 ; skirt
G1 X3.249 Y7.351 E.04901 ; skirt
G1 X3.739 Y6.588 E.02693 ; skirt
G1 X4.803 Y5.284 E.04996 ; skirt
G1 E-6 F43200 ; retract
;WIPE_START
G1 F6240
G1 X5.228 Y4.892 E-3.8 ; wipe and retract
;WIPE_END
G1 E-.2 F43200 ; retract
G1 Z.7 F7800 ; lift Z
G1 X201.382 Y199.426 ; move to first perimeter point
G1 Z.2 ; restore layer Z
M73 P27 R3
G1 E10.2 F12000 ;  ; unretract
;TYPE:Perimeter
;WIDTH:0.399999
G1 F1200
G1 X201.35 Y199.626 E.006 ; perimeter
G1 X201.13 Y200.185 E.01786 ; perimeter
G1 X200.842 Y200.597 E.01491 ; perimeter
G1 X200.398 Y200.99 E.01761 ; perimeter
G1 X199.947 Y201.241 E.01533 ; perimeter
G1 X199.462 Y201.394 E.0151 ; perimeter
G1 X198.976 Y201.443 E.01451 ; perimeter
G1 X11.044 Y201.443 E5.57993 ; perimeter
G1 X10.374 Y201.35 E.02006 ; perimeter
M73 P30 R3
G1 X9.815 Y201.13 E.01786 ; perimeter
G1 X9.403 Y200.842 E.01491 ; perimeter
G1 X9.01 Y200.398 E.01761 ; perimeter
G1 X8.759 Y199.947 E.01533 ; perimeter
G1 X8.606 Y199.462 E.0151 ; perimeter
G1 X8.557 Y198.976 E.01451 ; perimeter
G1 X8.557 Y13.239 E5.51476 ; perimeter
G1 X8.606 Y12.556 E.02034 ; perimeter
M73 P34 R3
G1 X8.747 Y11.906 E.01974 ; perimeter
G1 X8.98 Y11.283 E.01974 ; perimeter
G1 X9.298 Y10.699 E.01974 ; perimeter
G1 X9.697 Y10.167 E.01974 ; perimeter
G1 X10.167 Y9.697 E.01974 ; perimeter
G1 X10.699 Y9.298 E.01974 ; perimeter
G1 X11.283 Y8.98 E.01974 ; perimeter
G1 X11.906 Y8.747 E.01974 ; perimeter
G1 X12.556 Y8.606 E.01974 ; perimeter
G1 X13.239 Y8.557 E.02034 ; perimeter
G1 X198.956 Y8.557 E5.51419 ; perimeter
G1 X199.626 Y8.65 E.02006 ; perimeter
M73 P37 R2
G1 X200.185 Y8.87 E.01786 ; perimeter
G1 X200.597 Y9.158 E.01491 ; perimeter
G1 X200.99 Y9.602 E.01761 ; perimeter
G1 X201.241 Y10.053 E.01533 ; perimeter
G1 X201.394 Y10.538 E.0151 ; perimeter
G1 X201.443 Y11.044 E.01508 ; perimeter
G1 X201.443 Y198.956 E5.57936 ; perimeter
G1 X201.391 Y199.367 E.01228 ; perimeter
M73 P41 R2
G1 X201.757 Y199.486 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F1200
G1 X201.601 Y200.021 E.01655 ; perimeter
G1 X201.335 Y200.527 E.01694 ; perimeter
G1 X200.969 Y200.975 E.01718 ; perimeter
G1 X200.603 Y201.282 E.0142 ; perimeter
G1 X200.098 Y201.565 E.01718 ; perimeter
G1 X199.554 Y201.738 E.01694 ; perimeter
G1 X198.991 Y201.8 E.01681 ; perimeter
G1 X11.044 Y201.8 E5.5804 ; perimeter
G1 X10.514 Y201.757 E.01578 ; perimeter
M73 P44 R2
G1 X9.979 Y201.601 E.01655 ; perimeter
G1 X9.473 Y201.335 E.01694 ; perimeter
G1 X9.025 Y200.969 E.01718 ; perimeter
G1 X8.718 Y200.603 E.0142 ; perimeter
G1 X8.435 Y200.098 E.01718 ; perimeter
G1 X8.262 Y199.554 E.01694 ; perimeter
G1 X8.2 Y198.991 E.01681 ; perimeter
G1 X8.2 Y13.226 E5.5156 ; perimeter
G1 X8.252 Y12.505 E.02147 ; perimeter
M73 P48 R2
G1 X8.404 Y11.805 E.02126 ; perimeter
G1 X8.654 Y11.134 E.02126 ; perimeter
G1 X8.997 Y10.506 E.02126 ; perimeter
G1 X9.426 Y9.933 E.02126 ; perimeter
G1 X9.933 Y9.426 E.02126 ; perimeter
G1 X10.506 Y8.997 E.02126 ; perimeter
G1 X11.134 Y8.654 E.02126 ; perimeter
G1 X11.805 Y8.404 E.02126 ; perimeter
G1 X12.505 Y8.252 E.02126 ; perimeter
G1 X13.226 Y8.2 E.02147 ; perimeter
G1 X198.956 Y8.2 E5.51456 ; perimeter
G1 X199.636 Y8.283 E.02032 ; perimeter
M73 P51 R2
G1 X200.182 Y8.474 E.01718 ; perimeter
G1 X200.596 Y8.713 E.0142 ; perimeter
G1 X201.035 Y9.091 E.01718 ; perimeter
G1 X201.384 Y9.543 E.01694 ; perimeter
G1 X201.601 Y9.979 E.01448 ; perimeter
G1 X201.757 Y10.514 E.01653 ; perimeter
G1 X201.8 Y11.044 E.01578 ; perimeter
G1 X201.8 Y198.956 E5.57936 ; perimeter
G1 X201.762 Y199.426 E.014 ; perimeter
M73 P55 R2
G1 X201.379 Y199.617 F7800 ; move inwards before travel
G1 X200.518 Y199.292 ; move to first perimeter point
;TYPE:Perimeter
G1 F1200
G1 X200.509 Y199.361 E.00207 ; perimeter
G1 X200.295 Y199.855 E.016 ; perimeter
G1 X199.924 Y200.246 E.016 ; perimeter
G1 X199.443 Y200.487 E.016 ; perimeter
G1 X198.956 Y200.557 E.01458 ; perimeter
G1 X10.999 Y200.557 E5.58068 ; perimeter
G1 X10.639 Y200.509 E.01077 ; perimeter
M73 P58 R1
G1 X10.145 Y200.295 E.016 ; perimeter
G1 X9.754 Y199.924 E.016 ; perimeter
G1 X9.513 Y199.443 E.016 ; perimeter
G1 X9.443 Y198.956 E.01458 ; perimeter
G1 X9.443 Y13.218 E5.5148 ; perimeter
G1 X9.49 Y12.658 E.01669 ; perimeter
M73 P61 R1
G1 X9.609 Y12.148 E.01555 ; perimeter
G1 X9.794 Y11.659 E.01553 ; perimeter
G1 X10.04 Y11.197 E.01553 ; perimeter
G1 X10.351 Y10.764 E.01581 ; perimeter
M73 P62 R1
G1 X10.757 Y10.358 E.01707 ; perimeter
G1 X11.197 Y10.04 E.01611 ; perimeter
G1 X11.659 Y9.794 E.01553 ; perimeter
G1 X12.148 Y9.609 E.01553 ; perimeter
G1 X12.658 Y9.49 E.01555 ; perimeter
G1 X13.255 Y9.443 E.01777 ; perimeter
G1 X199.001 Y9.443 E5.51504 ; perimeter
G1 X199.361 Y9.491 E.01077 ; perimeter
M73 P65 R1
G1 X199.855 Y9.705 E.016 ; perimeter
G1 X200.246 Y10.076 E.016 ; perimeter
G1 X200.487 Y10.557 E.016 ; perimeter
G1 X200.557 Y11.044 E.01458 ; perimeter
G1 X200.557 Y199.001 E5.58068 ; perimeter
G1 X200.526 Y199.232 E.00692 ; perimeter
M73 P68 R1
G1 X200.174 Y199.238 F7800 ; move to first perimeter point
;TYPE:External perimeter
G1 F1200
G1 X200.021 Y199.626 E.01235 ; perimeter
G1 X199.746 Y199.937 E.01235 ; perimeter
G1 X199.38 Y200.136 E.01235 ; perimeter
G1 X198.956 Y200.2 E.01274 ; perimeter
G1 X10.999 Y200.2 E5.58068 ; perimeter
G1 X10.762 Y200.174 E.0071 ; perimeter
M73 P72 R1
G1 X10.374 Y200.021 E.01235 ; perimeter
G1 X10.063 Y199.746 E.01235 ; perimeter
G1 X9.864 Y199.38 E.01235 ; perimeter
G1 X9.8 Y198.956 E.01274 ; perimeter
G1 X9.8 Y13.218 E5.5148 ; perimeter
G1 X9.846 Y12.689 E.01577 ; perimeter
M73 P75 R1
G1 X10.001 Y12.064 E.01911 ; perimeter
G1 X10.251 Y11.523 E.01769 ; perimeter
G1 X10.59 Y11.034 E.01769 ; perimeter
G1 X11.01 Y10.61 E.01769 ; perimeter
G1 X11.496 Y10.266 E.01769 ; perimeter
G1 X12.035 Y10.012 E.01769 ; perimeter
G1 X12.61 Y9.855 E.01769 ; perimeter
G1 X13.255 Y9.8 E.01921 ; perimeter
G1 X199.001 Y9.8 E5.51504 ; perimeter
G1 X199.238 Y9.826 E.0071 ; perimeter
M73 P79 R0
G1 X199.626 Y9.979 E.01235 ; perimeter
G1 X199.937 Y10.254 E.01235 ; perimeter
G1 X200.136 Y10.62 E.01235 ; perimeter
G1 X200.2 Y11.044 E.01274 ; perimeter
G1 X200.2 Y199.001 E5.58068 ; perimeter
G1 X200.18 Y199.179 E.00531 ; perimeter
M73 P82 R0
G1 X200.46 Y199.518 F7800 ; move inwards before travel
G1 X200.968 Y199.347 ; move to first perimeter point
;TYPE:Perimeter
;WIDTH:0.56779
G1 F1200
G1 X200.802 Y199.845 E.02289 ; perimeter
G1 X200.633 Y200.139 E.0148 ; perimeter
G1 X200.284 Y200.531 E.02289 ; perimeter
G1 X199.838 Y200.806 E.0229 ; perimeter
G1 X199.519 Y200.922 E.01479 ; perimeter
;WIDTH:0.571682
G1 X198.956 Y201 E.02499 ; perimeter
G1 X11.044 Y201 E8.26191 ; perimeter
G1 X10.653 Y200.968 E.01723 ; perimeter
;WIDTH:0.567794
M73 P86 R0
G1 X10.155 Y200.802 E.02289 ; perimeter
G1 X9.861 Y200.633 E.0148 ; perimeter
G1 X9.469 Y200.284 E.02289 ; perimeter
G1 X9.194 Y199.838 E.0229 ; perimeter
G1 X9.078 Y199.519 E.01479 ; perimeter
;WIDTH:0.571684
G1 X9 Y198.956 E.02499 ; perimeter
G1 X9.006 Y13.133 E8.17008 ; perimeter
;WIDTH:0.568716
G1 X9.054 Y12.571 E.02465 ; perimeter
;WIDTH:0.580176
M73 P89 R0
G1 X9.177 Y12.032 E.02469 ; perimeter
;WIDTH:0.581234
G1 X9.388 Y11.469 E.0269 ; perimeter
G1 X9.675 Y10.941 E.0269 ; perimeter
;WIDTH:0.578058
G1 X10.045 Y10.444 E.02757 ; perimeter
;WIDTH:0.5708
G1 X10.457 Y10.032 E.0256 ; perimeter
;WIDTH:0.578058
G1 X10.941 Y9.675 E.02676 ; perimeter
;WIDTH:0.581234
G1 X11.469 Y9.388 E.0269 ; perimeter
G1 X12.032 Y9.177 E.0269 ; perimeter
;WIDTH:0.580176
G1 X12.619 Y9.047 E.02686 ; perimeter
;WIDTH:0.574882
G1 X13.255 Y9 E.02819 ; perimeter
;WIDTH:0.57168
G1 X198.956 Y9 E8.16467 ; perimeter
G1 X199.347 Y9.032 E.01723 ; perimeter
;WIDTH:0.56779
M73 P92 R0
G1 X199.845 Y9.198 E.02289 ; perimeter
G1 X200.139 Y9.367 E.0148 ; perimeter
G1 X200.531 Y9.716 E.02289 ; perimeter
G1 X200.806 Y10.162 E.0229 ; perimeter
G1 X200.922 Y10.481 E.01479 ; perimeter
;WIDTH:0.571682
M73 P93 R0
G1 X201 Y11.044 E.02499 ; perimeter
G1 X201 Y198.956 E8.26191 ; perimeter
G1 X200.973 Y199.287 E.0146 ; perimeter
M73 P96 R0
G1 E-6 F43200 ; retract
;WIPE_START
G1 F6240;_WIPE
G1 X200.804 Y199.84 E-3.8 ; wipe and retract
;WIPE_END
G1 E-.2 F43200 ; retract
G1 Z.7 F7800 ; lift Z
M107 ; disable fan
;TYPE:Custom
; Filament-specific end gcode
G1 E-1.0 F2100 ; retract
G92 E0.0
G1 Z30.2 E-34.0 F720 ; move print head up & retract filament
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 X0 Y105 F3000 ; park print head
M84 ; disable motors
M73 P100 R0
; filament used [mm] = 148.69
; filament used [cm3] = 0.36
; filament used [g] = 0.44
; filament cost = 0.02
; total filament used [g] = 0.44
; total filament cost = 0.02
; estimated printing time (normal mode) = 4m 36s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,210x0,210x210,0x210
; bed_temperature = 35
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 75
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = ;"printer_notes=~/.*PRINTER_VENDOR_ANYCUBIC.*/ and printer_notes=~/.*PRINTER_MODEL_I3_MEGA.*/"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "Generic PLA @MEGA"
; default_print_profile = 0.15mm QUALITY @MEGA
; deretract_speed = 200
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G1 E-1.0 F2100 ; retract\nG92 E0.0\nG1{if max_layer_z < max_print_height} Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} E-34.0 F720 ; move print head up & retract filament\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nG1 X0 Y105 F3000 ; park print head\nM84 ; disable motors
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 80
; extruder_clearance_radius = 80
; extruder_colour = #808080
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF3232
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 50
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 10
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA @MEGA - Copy"
; filament_soluble = 0
; filament_spool_weight = 1000
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 25%
; fill_pattern = gyroid
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 65
; first_layer_extrusion_width = 200%
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 225
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"Generic PLA @MEGA";"Anycubic i3 Mega"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.25
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 3000
; machine_max_acceleration_y = 2000
; machine_max_acceleration_z = 60
; machine_max_feedrate_e = 60
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 6
; machine_max_jerk_e = 5
; machine_max_jerk_x = 10
; machine_max_jerk_y = 10
; machine_max_jerk_z = 0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 66
; max_layer_height = 0.33
; max_print_height = 190
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 25
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = print.3mf (main.3mf (main.3mf (print.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (SmartTemperatureTower_PLA_180-225.3mf (my print settings 0.3)))))))))))))))
; printer_model = I3MEGA
; printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_ANYCUBIC\nPRINTER_MODEL_I3_MEGA\nPRINTER_HAS_BOWDEN
; printer_settings_id = Anycubic i3 Mega - 0.8mm
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 100%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 60%
; retract_layer_change = 1
; retract_length = 10
; retract_length_toolchange = 10
; retract_lift = 0.5
; retract_lift_above = 0
; retract_lift_below = 185
; retract_restart_extra = 0.2
; retract_restart_extra_toolchange = 0
; retract_speed = 720
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM204 S[machine_max_acceleration_extruding] T[machine_max_acceleration_retracting]\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nG28 ; home all\nG1 Y1.0 Z0.3 F1000 ; move print head up\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG92 E0.0\n; initial load\nG1 X205.0 E19 F1000\nG1 Y1.6\nG1 X5.0 E19 F1000\nG92 E0.0\n; intro line\nG1 Y2.0 Z0.2 F1000\nG1 X65.0 E9.0 F1000\nG1 X105.0 E12.5 F1000\nG92 E0.0
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.3
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 1
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 16
; thumbnails = 16x16,220x124
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 15
; top_solid_layers = 5
; top_solid_min_thickness = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
