name: carousell-search-scan

on:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: helloworld
        run: |
          cd carousell-scripts/search-scan
            npm i
            npm run test
            npm run publish
          cd ..

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: failure-troubleshoot
          path: |
            carousell-scripts/search-scan/cypress/screenshots
            carousell-scripts/search-scan/cypress/videos
