name: product-exercise

on:
  push:
  schedule:
    - cron: '20 9-23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        continue-on-error: true
        timeout-minutes: 120
        env: # Or as an environment variable
          ENV_KEYWORD_LIST: ${{ secrets.ENV_KEYWORD_LIST }}
          ENV_USER_LIST: ${{ secrets.ENV_USER_LIST }}
          ENV_MIN_CLICK: ${{ secrets.ENV_MIN_CLICK }}
          ENV_MAX_CLICK: ${{ secrets.ENV_MAX_CLICK }}
        run: |
          cd carousell-scripts/product-exercise
            ./retest.sh 
          cd ..

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   # If you're changing the branch from main,
      #   # also change the `main` in `refs/heads/main`
      #   # below accordingly.
      #   # if: ${{ github.ref == 'refs/heads/main' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     keep_files: true
      #     publish_dir: carousell-scripts/search-scan/cypress/reports/html

      # - uses: actions/upload-artifact@v2 # upload test results
      #   if: failure() || success()
      #   with:
      #     name: failure-troubleshoot
      #     path: |
      #       carousell-scripts/search-scan/cypress/screenshots
      #       carousell-scripts/search-scan/cypress/videos
